spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mariadb://localhost:3306/bootjpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    cache: false